from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Theme:
    name: str
    is_dark: bool
    colors: dict[str, str]


BASE_TOKENS = {
    "success": "#2f9e44",
    "warning": "#b76b00",
    "error": "#c73636",
}


def _theme(name: str, is_dark: bool, colors: dict[str, str]) -> Theme:
    merged = {**BASE_TOKENS, **colors}
    design_tokens = {
        "app_bg": merged["background"],
        "card_bg": merged["surface"],
        "card_bg_raised": merged["surface_raised"],
        "card_border": merged["border"],
        "card_border_strong": merged.get("border_strong", merged["border"]),
        "canvas_bg": merged["workspace_bg"],
        "text_muted": merged["text_secondary"],
        "button_border": merged["border"],
        "primary_button_bg": merged["accent"],
        "primary_button_hover": merged["accent_hover"],
        "input_border": merged["border"],
        "table_row_bg": merged["table_bg"],
        "table_selected_bg": merged["selection_bg"],
        "table_selected_fg": merged["selection_fg"],
        "scrollbar": merged.get("scrollbar", merged.get("border_strong", merged["border"])),
        "divider": merged.get("divider", merged["border"]),
        "toolbar_bg": merged.get("toolbar_bg", merged["surface"]),
        "tip_bg": merged.get("tip_bg", merged["surface_raised"]),
        "danger": merged["error"],
    }
    merged.update(design_tokens)
    aliases = {
        "bg": merged["app_bg"],
        "panel": merged["card_bg"],
        "fg": merged["text_primary"],
        "muted": merged["text_muted"],
        "accent": merged["accent"],
        "entry_bg": merged["input_bg"],
        "entry_fg": merged["text_primary"],
        "border": merged["card_border"],
        "sel_bg": merged["selection_bg"],
        "sel_fg": merged["selection_fg"],
        "tree_bg": merged["table_row_bg"],
        "tree_alt": merged["table_alt_bg"],
        "tree_head_bg": merged["table_header_bg"],
        "tree_head_fg": merged["text_primary"],
        "progress": merged["accent"],
        "preview_bg": merged["workspace_bg"],
        "preview_border": merged["workspace_border"],
        "preview_panel": merged["preview_panel"],
        "preview_content": merged["preview_content"],
        "preview_bleed": merged["preview_bleed"],
        "preview_overlap": merged["preview_overlap"],
        "preview_label_bg": merged["preview_label_bg"],
        "preview_label_fg": merged["preview_label_fg"],
    }
    merged.update(aliases)
    return Theme(name=name, is_dark=is_dark, colors=merged)


THEMES: dict[str, Theme] = {
    "Soft Blue": _theme(
        "Soft Blue",
        False,
        {
            "background": "#eef5fb",
            "surface": "#ffffff",
            "surface_raised": "#f8fbff",
            "border": "#c9d8ea",
            "border_strong": "#9fb8d4",
            "text_primary": "#142033",
            "text_secondary": "#53657d",
            "accent": "#1f66d1",
            "accent_hover": "#1854ad",
            "button_bg": "#ffffff",
            "button_hover": "#e8f1ff",
            "input_bg": "#ffffff",
            "table_bg": "#ffffff",
            "table_alt_bg": "#f4f8fd",
            "table_header_bg": "#edf4fc",
            "selection_bg": "#d9eaff",
            "selection_fg": "#10213a",
            "workspace_bg": "#f7fbff",
            "workspace_border": "#5f7896",
            "preview_panel": "#126bd8",
            "preview_content": "#4d5d71",
            "preview_bleed": "#c83f43",
            "preview_overlap": "#9a6100",
            "preview_label_bg": "#ffffff",
            "preview_label_fg": "#10213a",
        },
    ),
    "Minimal Light": _theme(
        "Minimal Light",
        False,
        {
            "background": "#f5f7fa",
            "surface": "#ffffff",
            "surface_raised": "#fbfcfe",
            "border": "#d4dae3",
            "border_strong": "#aab4c2",
            "text_primary": "#151b26",
            "text_secondary": "#596579",
            "accent": "#285fd6",
            "accent_hover": "#1f4fb6",
            "button_bg": "#ffffff",
            "button_hover": "#eef3ff",
            "input_bg": "#ffffff",
            "table_bg": "#ffffff",
            "table_alt_bg": "#f7f9fc",
            "table_header_bg": "#f0f3f8",
            "selection_bg": "#dbe8ff",
            "selection_fg": "#10213a",
            "workspace_bg": "#fafcff",
            "workspace_border": "#667386",
            "preview_panel": "#1d65d8",
            "preview_content": "#566071",
            "preview_bleed": "#bf3d3d",
            "preview_overlap": "#8f5b00",
            "preview_label_bg": "#ffffff",
            "preview_label_fg": "#151b26",
        },
    ),
    "Dark Pro": _theme(
        "Dark Pro",
        True,
        {
            "background": "#151922",
            "surface": "#202633",
            "surface_raised": "#252c3a",
            "border": "#394354",
            "border_strong": "#536176",
            "text_primary": "#f3f6fb",
            "text_secondary": "#b8c2d2",
            "accent": "#4da3ff",
            "accent_hover": "#79baff",
            "button_bg": "#252c3a",
            "button_hover": "#30394b",
            "input_bg": "#151b26",
            "table_bg": "#1a202b",
            "table_alt_bg": "#202735",
            "table_header_bg": "#252d3c",
            "selection_bg": "#174f8f",
            "selection_fg": "#ffffff",
            "workspace_bg": "#10151d",
            "workspace_border": "#64748b",
            "preview_panel": "#62b3ff",
            "preview_content": "#d7e1ef",
            "preview_bleed": "#ff6b6b",
            "preview_overlap": "#ffd166",
            "preview_label_bg": "#0d1118",
            "preview_label_fg": "#ffffff",
        },
    ),
    "Industrial Gray": _theme(
        "Industrial Gray",
        False,
        {
            "background": "#eceff1",
            "surface": "#f8f9fa",
            "surface_raised": "#ffffff",
            "border": "#bdc5ce",
            "border_strong": "#89939f",
            "text_primary": "#1f252b",
            "text_secondary": "#56616d",
            "accent": "#315f88",
            "accent_hover": "#254c70",
            "button_bg": "#f8f9fa",
            "button_hover": "#e5eaee",
            "input_bg": "#ffffff",
            "table_bg": "#ffffff",
            "table_alt_bg": "#f1f3f5",
            "table_header_bg": "#e0e5ea",
            "selection_bg": "#d3e1ec",
            "selection_fg": "#172433",
            "workspace_bg": "#f3f5f6",
            "workspace_border": "#68727e",
            "preview_panel": "#245f9f",
            "preview_content": "#4a4f57",
            "preview_bleed": "#b93f3f",
            "preview_overlap": "#895a00",
            "preview_label_bg": "#ffffff",
            "preview_label_fg": "#1f252b",
        },
    ),
    "Blueprint": _theme(
        "Blueprint",
        True,
        {
            "background": "#0f172a",
            "surface": "#162238",
            "surface_raised": "#1b2b47",
            "border": "#304a70",
            "border_strong": "#4f72a1",
            "text_primary": "#edf6ff",
            "text_secondary": "#b8cbe4",
            "accent": "#38bdf8",
            "accent_hover": "#7dd3fc",
            "button_bg": "#1b2b47",
            "button_hover": "#213a61",
            "input_bg": "#0e1a2d",
            "table_bg": "#122037",
            "table_alt_bg": "#172840",
            "table_header_bg": "#1c3355",
            "selection_bg": "#075985",
            "selection_fg": "#ffffff",
            "workspace_bg": "#0b1324",
            "workspace_border": "#67e8f9",
            "preview_panel": "#38bdf8",
            "preview_content": "#e0f2fe",
            "preview_bleed": "#fb7185",
            "preview_overlap": "#fde047",
            "preview_label_bg": "#07111f",
            "preview_label_fg": "#ffffff",
        },
    ),
    "Professional Dark": _theme(
        "Professional Dark",
        True,
        {
            "background": "#1f2023",
            "surface": "#26282c",
            "surface_raised": "#2d3036",
            "border": "#454a52",
            "border_strong": "#626a75",
            "text_primary": "#f0f2f4",
            "text_secondary": "#b7bcc5",
            "accent": "#4f9cf9",
            "accent_hover": "#75b4ff",
            "button_bg": "#2d3036",
            "button_hover": "#363b43",
            "input_bg": "#30333a",
            "table_bg": "#22252a",
            "table_alt_bg": "#292d33",
            "table_header_bg": "#30343b",
            "selection_bg": "#295d93",
            "selection_fg": "#ffffff",
            "workspace_bg": "#1b1d20",
            "workspace_border": "#d8dde6",
            "preview_panel": "#57a6ff",
            "preview_content": "#dce3ec",
            "preview_bleed": "#e65f5c",
            "preview_overlap": "#f2b84b",
            "preview_label_bg": "#111316",
            "preview_label_fg": "#ffffff",
        },
    ),
    "Professional Light": _theme(
        "Professional Light",
        False,
        {
            "background": "#eef1f5",
            "surface": "#ffffff",
            "surface_raised": "#fbfcfd",
            "border": "#c9d0da",
            "border_strong": "#a2adba",
            "text_primary": "#20242a",
            "text_secondary": "#5d6673",
            "accent": "#246fc6",
            "accent_hover": "#1a5aa4",
            "button_bg": "#ffffff",
            "button_hover": "#edf3fb",
            "input_bg": "#ffffff",
            "table_bg": "#ffffff",
            "table_alt_bg": "#f3f5f8",
            "table_header_bg": "#e8edf3",
            "selection_bg": "#cfe3ff",
            "selection_fg": "#10233d",
            "workspace_bg": "#f7f8fa",
            "workspace_border": "#1f2933",
            "preview_panel": "#126bd8",
            "preview_content": "#4b5563",
            "preview_bleed": "#cf3f3f",
            "preview_overlap": "#8a5200",
            "preview_label_bg": "#ffffff",
            "preview_label_fg": "#111827",
        },
    ),
    "Graphite": _theme(
        "Graphite",
        True,
        {
            "background": "#242424",
            "surface": "#2f3032",
            "surface_raised": "#37393c",
            "border": "#56585b",
            "border_strong": "#74777c",
            "text_primary": "#eeeeee",
            "text_secondary": "#c1c1c1",
            "accent": "#8aa4b8",
            "accent_hover": "#a9c1d3",
            "button_bg": "#37393c",
            "button_hover": "#414449",
            "input_bg": "#3a3b3d",
            "table_bg": "#2a2b2d",
            "table_alt_bg": "#323437",
            "table_header_bg": "#3a3c40",
            "selection_bg": "#516170",
            "selection_fg": "#ffffff",
            "workspace_bg": "#202123",
            "workspace_border": "#e1e4e8",
            "preview_panel": "#9ec5e6",
            "preview_content": "#d7dce2",
            "preview_bleed": "#dd6b6b",
            "preview_overlap": "#e6bd5f",
            "preview_label_bg": "#151617",
            "preview_label_fg": "#ffffff",
        },
    ),
    "Midnight": _theme(
        "Midnight",
        True,
        {
            "background": "#171c26",
            "surface": "#202838",
            "surface_raised": "#263047",
            "border": "#3c4a63",
            "border_strong": "#566887",
            "text_primary": "#edf2f7",
            "text_secondary": "#aeb9c8",
            "accent": "#67b7ff",
            "accent_hover": "#8ccbff",
            "button_bg": "#263047",
            "button_hover": "#2d3a55",
            "input_bg": "#283246",
            "table_bg": "#1c2331",
            "table_alt_bg": "#242d3e",
            "table_header_bg": "#2a3448",
            "selection_bg": "#285f8f",
            "selection_fg": "#ffffff",
            "workspace_bg": "#121722",
            "workspace_border": "#dce9f8",
            "preview_panel": "#77c7ff",
            "preview_content": "#d5deea",
            "preview_bleed": "#ff7373",
            "preview_overlap": "#f0c861",
            "preview_label_bg": "#0d1119",
            "preview_label_fg": "#ffffff",
        },
    ),
    "Neutral Gray": _theme(
        "Neutral Gray",
        False,
        {
            "background": "#e9ecef",
            "surface": "#f8f9fa",
            "surface_raised": "#ffffff",
            "border": "#bfc5cc",
            "border_strong": "#9aa3ad",
            "text_primary": "#24272b",
            "text_secondary": "#5f6670",
            "accent": "#4c6f8f",
            "accent_hover": "#385a77",
            "button_bg": "#f8f9fa",
            "button_hover": "#e8ecef",
            "input_bg": "#ffffff",
            "table_bg": "#ffffff",
            "table_alt_bg": "#f1f3f5",
            "table_header_bg": "#dee2e6",
            "selection_bg": "#d7e4ee",
            "selection_fg": "#1d2f42",
            "workspace_bg": "#f4f5f6",
            "workspace_border": "#222222",
            "preview_panel": "#245f9f",
            "preview_content": "#4a4f57",
            "preview_bleed": "#c94b4b",
            "preview_overlap": "#8f5b00",
            "preview_label_bg": "#ffffff",
            "preview_label_fg": "#1f2328",
        },
    ),
    "High Contrast": _theme(
        "High Contrast",
        True,
        {
            "background": "#111111",
            "surface": "#1d1d1d",
            "surface_raised": "#242424",
            "border": "#ffffff",
            "border_strong": "#ffffff",
            "text_primary": "#ffffff",
            "text_secondary": "#e0e0e0",
            "accent": "#00a3ff",
            "accent_hover": "#69caff",
            "button_bg": "#1d1d1d",
            "button_hover": "#2a2a2a",
            "input_bg": "#000000",
            "table_bg": "#000000",
            "table_alt_bg": "#1a1a1a",
            "table_header_bg": "#2a2a2a",
            "selection_bg": "#005bbb",
            "selection_fg": "#ffffff",
            "workspace_bg": "#000000",
            "workspace_border": "#ffffff",
            "preview_panel": "#00a3ff",
            "preview_content": "#ffffff",
            "preview_bleed": "#ff4d4d",
            "preview_overlap": "#ffd23f",
            "preview_label_bg": "#000000",
            "preview_label_fg": "#ffffff",
        },
    ),
    "Warm Dark": _theme(
        "Warm Dark",
        True,
        {
            "background": "#24211f",
            "surface": "#2e2a27",
            "surface_raised": "#39332f",
            "border": "#5a514a",
            "border_strong": "#75695e",
            "text_primary": "#f2eee9",
            "text_secondary": "#c9c0b6",
            "accent": "#d7a35d",
            "accent_hover": "#efbb72",
            "button_bg": "#39332f",
            "button_hover": "#443c36",
            "input_bg": "#39332f",
            "table_bg": "#282421",
            "table_alt_bg": "#332e2a",
            "table_header_bg": "#3a342f",
            "selection_bg": "#76542b",
            "selection_fg": "#ffffff",
            "workspace_bg": "#201d1a",
            "workspace_border": "#f1e8dc",
            "preview_panel": "#efbb72",
            "preview_content": "#e6ded5",
            "preview_bleed": "#df6a61",
            "preview_overlap": "#f0c15d",
            "preview_label_bg": "#171411",
            "preview_label_fg": "#ffffff",
        },
    ),
}


THEME_NAMES = list(THEMES.keys())
DEFAULT_THEME = "Soft Blue"
LEGACY_THEME_MAP = {
    "dark": "Dark Pro",
    "light": "Minimal Light",
}


def normalize_theme_name(name: str | None) -> str:
    if not name:
        return DEFAULT_THEME
    mapped = LEGACY_THEME_MAP.get(str(name).lower(), name)
    return mapped if mapped in THEMES else DEFAULT_THEME


def get_theme(name: str | None) -> Theme:
    return THEMES[normalize_theme_name(name)]
