from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Theme:
    name: str
    is_dark: bool
    colors: dict[str, str]


BASE_TOKENS = {
    "success": "#2f9e44",
    "warning": "#d9822b",
    "error": "#d64545",
}


THEMES: dict[str, Theme] = {
    "Professional Dark": Theme(
        name="Professional Dark",
        is_dark=True,
        colors={
            **BASE_TOKENS,
            "bg": "#1f2023",
            "panel": "#26282c",
            "fg": "#f0f2f4",
            "muted": "#b7bcc5",
            "accent": "#4f9cf9",
            "entry_bg": "#30333a",
            "entry_fg": "#f4f6f8",
            "border": "#454a52",
            "sel_bg": "#295d93",
            "sel_fg": "#ffffff",
            "tree_bg": "#22252a",
            "tree_alt": "#292d33",
            "tree_head_bg": "#30343b",
            "tree_head_fg": "#f0f2f4",
            "progress": "#4f9cf9",
            "preview_bg": "#1b1d20",
            "preview_border": "#d8dde6",
            "preview_panel": "#57a6ff",
            "preview_content": "#dce3ec",
            "preview_bleed": "#e65f5c",
            "preview_overlap": "#f2b84b",
            "preview_label_bg": "#111316",
            "preview_label_fg": "#ffffff",
        },
    ),
    "Professional Light": Theme(
        name="Professional Light",
        is_dark=False,
        colors={
            **BASE_TOKENS,
            "bg": "#eef1f5",
            "panel": "#ffffff",
            "fg": "#20242a",
            "muted": "#5d6673",
            "accent": "#246fc6",
            "entry_bg": "#ffffff",
            "entry_fg": "#20242a",
            "border": "#c9d0da",
            "sel_bg": "#cfe3ff",
            "sel_fg": "#10233d",
            "tree_bg": "#ffffff",
            "tree_alt": "#f3f5f8",
            "tree_head_bg": "#e8edf3",
            "tree_head_fg": "#20242a",
            "progress": "#246fc6",
            "preview_bg": "#f7f8fa",
            "preview_border": "#1f2933",
            "preview_panel": "#126bd8",
            "preview_content": "#4b5563",
            "preview_bleed": "#cf3f3f",
            "preview_overlap": "#b56b00",
            "preview_label_bg": "#ffffff",
            "preview_label_fg": "#111827",
        },
    ),
    "Graphite": Theme(
        name="Graphite",
        is_dark=True,
        colors={
            **BASE_TOKENS,
            "bg": "#242424",
            "panel": "#2f3032",
            "fg": "#eeeeee",
            "muted": "#c1c1c1",
            "accent": "#8aa4b8",
            "entry_bg": "#3a3b3d",
            "entry_fg": "#f2f2f2",
            "border": "#56585b",
            "sel_bg": "#516170",
            "sel_fg": "#ffffff",
            "tree_bg": "#2a2b2d",
            "tree_alt": "#323437",
            "tree_head_bg": "#3a3c40",
            "tree_head_fg": "#f2f2f2",
            "progress": "#8aa4b8",
            "preview_bg": "#202123",
            "preview_border": "#e1e4e8",
            "preview_panel": "#9ec5e6",
            "preview_content": "#d7dce2",
            "preview_bleed": "#dd6b6b",
            "preview_overlap": "#e6bd5f",
            "preview_label_bg": "#151617",
            "preview_label_fg": "#ffffff",
        },
    ),
    "Midnight": Theme(
        name="Midnight",
        is_dark=True,
        colors={
            **BASE_TOKENS,
            "bg": "#171c26",
            "panel": "#202838",
            "fg": "#edf2f7",
            "muted": "#aeb9c8",
            "accent": "#67b7ff",
            "entry_bg": "#283246",
            "entry_fg": "#f5f8fb",
            "border": "#3c4a63",
            "sel_bg": "#285f8f",
            "sel_fg": "#ffffff",
            "tree_bg": "#1c2331",
            "tree_alt": "#242d3e",
            "tree_head_bg": "#2a3448",
            "tree_head_fg": "#edf2f7",
            "progress": "#67b7ff",
            "preview_bg": "#121722",
            "preview_border": "#dce9f8",
            "preview_panel": "#77c7ff",
            "preview_content": "#d5deea",
            "preview_bleed": "#ff7373",
            "preview_overlap": "#f0c861",
            "preview_label_bg": "#0d1119",
            "preview_label_fg": "#ffffff",
        },
    ),
    "Neutral Gray": Theme(
        name="Neutral Gray",
        is_dark=False,
        colors={
            **BASE_TOKENS,
            "bg": "#e9ecef",
            "panel": "#f8f9fa",
            "fg": "#24272b",
            "muted": "#5f6670",
            "accent": "#4c6f8f",
            "entry_bg": "#ffffff",
            "entry_fg": "#24272b",
            "border": "#bfc5cc",
            "sel_bg": "#d7e4ee",
            "sel_fg": "#1d2f42",
            "tree_bg": "#ffffff",
            "tree_alt": "#f1f3f5",
            "tree_head_bg": "#dee2e6",
            "tree_head_fg": "#24272b",
            "progress": "#4c6f8f",
            "preview_bg": "#f4f5f6",
            "preview_border": "#222222",
            "preview_panel": "#245f9f",
            "preview_content": "#4a4f57",
            "preview_bleed": "#c94b4b",
            "preview_overlap": "#a86400",
            "preview_label_bg": "#ffffff",
            "preview_label_fg": "#1f2328",
        },
    ),
    "High Contrast": Theme(
        name="High Contrast",
        is_dark=True,
        colors={
            **BASE_TOKENS,
            "bg": "#111111",
            "panel": "#1d1d1d",
            "fg": "#ffffff",
            "muted": "#e0e0e0",
            "accent": "#00a3ff",
            "entry_bg": "#000000",
            "entry_fg": "#ffffff",
            "border": "#ffffff",
            "sel_bg": "#005bbb",
            "sel_fg": "#ffffff",
            "tree_bg": "#000000",
            "tree_alt": "#1a1a1a",
            "tree_head_bg": "#2a2a2a",
            "tree_head_fg": "#ffffff",
            "progress": "#00a3ff",
            "preview_bg": "#000000",
            "preview_border": "#ffffff",
            "preview_panel": "#00a3ff",
            "preview_content": "#ffffff",
            "preview_bleed": "#ff4d4d",
            "preview_overlap": "#ffd23f",
            "preview_label_bg": "#000000",
            "preview_label_fg": "#ffffff",
        },
    ),
    "Soft Blue": Theme(
        name="Soft Blue",
        is_dark=False,
        colors={
            **BASE_TOKENS,
            "bg": "#eaf1f8",
            "panel": "#f8fbff",
            "fg": "#1f2d3d",
            "muted": "#60758c",
            "accent": "#357abd",
            "entry_bg": "#ffffff",
            "entry_fg": "#1f2d3d",
            "border": "#bfd0e2",
            "sel_bg": "#d6e9fb",
            "sel_fg": "#123252",
            "tree_bg": "#ffffff",
            "tree_alt": "#f0f6fc",
            "tree_head_bg": "#dceaf7",
            "tree_head_fg": "#1f2d3d",
            "progress": "#357abd",
            "preview_bg": "#f5f9fd",
            "preview_border": "#17324d",
            "preview_panel": "#126bd8",
            "preview_content": "#536273",
            "preview_bleed": "#ca4b4b",
            "preview_overlap": "#a86b00",
            "preview_label_bg": "#ffffff",
            "preview_label_fg": "#102840",
        },
    ),
    "Warm Dark": Theme(
        name="Warm Dark",
        is_dark=True,
        colors={
            **BASE_TOKENS,
            "bg": "#24211f",
            "panel": "#2e2a27",
            "fg": "#f2eee9",
            "muted": "#c9c0b6",
            "accent": "#d7a35d",
            "entry_bg": "#39332f",
            "entry_fg": "#f7f2ec",
            "border": "#5a514a",
            "sel_bg": "#76542b",
            "sel_fg": "#ffffff",
            "tree_bg": "#282421",
            "tree_alt": "#332e2a",
            "tree_head_bg": "#3a342f",
            "tree_head_fg": "#f2eee9",
            "progress": "#d7a35d",
            "preview_bg": "#201d1a",
            "preview_border": "#f1e8dc",
            "preview_panel": "#efbb72",
            "preview_content": "#e6ded5",
            "preview_bleed": "#df6a61",
            "preview_overlap": "#f0c15d",
            "preview_label_bg": "#171411",
            "preview_label_fg": "#ffffff",
        },
    ),
}


THEME_NAMES = list(THEMES.keys())
DEFAULT_THEME = "Professional Dark"
LEGACY_THEME_MAP = {
    "dark": "Professional Dark",
    "light": "Professional Light",
}


def normalize_theme_name(name: str | None) -> str:
    if not name:
        return DEFAULT_THEME
    mapped = LEGACY_THEME_MAP.get(str(name).lower(), name)
    return mapped if mapped in THEMES else DEFAULT_THEME


def get_theme(name: str | None) -> Theme:
    return THEMES[normalize_theme_name(name)]
